name: Pre-Deploy Quality Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Build project
        run: pnpm build

      - name: Test build output
        run: |
          if [ -d ".next" ]; then
            echo "✅ Build successful - .next directory exists"
          else
            echo "❌ Build failed - .next directory missing"
            exit 1
          fi
